// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvcx7v_GaXrN6Tu4X0sQv9wPOyLu27kHU',
    appId: '1:762424845985:web:721f8c812baed8e79fb2e0',
    messagingSenderId: '762424845985',
    projectId: 'carpark-df96f',
    authDomain: 'carpark-df96f.firebaseapp.com',
    storageBucket: 'carpark-df96f.firebasestorage.app',
    measurementId: 'G-MXY2T0VSBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvxHK5_4jJVAuIYOaqcAA8pDk7NtyvP0',
    appId: '1:762424845985:android:7bec8fea9e4efc419fb2e0',
    messagingSenderId: '762424845985',
    projectId: 'carpark-df96f',
    storageBucket: 'carpark-df96f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgEPzNtov5Hj9O2IXNTrtql2Tn87VOG_4',
    appId: '1:762424845985:ios:66f4c65c39133c6e9fb2e0',
    messagingSenderId: '762424845985',
    projectId: 'carpark-df96f',
    storageBucket: 'carpark-df96f.firebasestorage.app',
    iosBundleId: 'com.xolile.tapzpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgEPzNtov5Hj9O2IXNTrtql2Tn87VOG_4',
    appId: '1:762424845985:ios:66f4c65c39133c6e9fb2e0',
    messagingSenderId: '762424845985',
    projectId: 'carpark-df96f',
    storageBucket: 'carpark-df96f.firebasestorage.app',
    iosBundleId: 'com.xolile.tapzpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvcx7v_GaXrN6Tu4X0sQv9wPOyLu27kHU',
    appId: '1:762424845985:web:bd973ceb9a45d1ac9fb2e0',
    messagingSenderId: '762424845985',
    projectId: 'carpark-df96f',
    authDomain: 'carpark-df96f.firebaseapp.com',
    storageBucket: 'carpark-df96f.firebasestorage.app',
    measurementId: 'G-B2HNSK933Q',
  );
}
